require 'faraday'
require 'faraday_middleware'
require 'slop'

require 'openbd/resources/base_resource'
require 'openbd/resources/hanmoto'
require 'openbd/resources/onix'
require 'openbd/resources/summary'
require 'openbd/resources/openbd_item'
require 'openbd/responses/base_response'
require 'openbd/responses/coverage'
require 'openbd/responses/Get'
require 'openbd/responses/schema'
require 'openbd/version'
require 'openbd/client'
require 'openbd/openbd_cli'
